### ISSUE TITLE
账户balance显示不一致(命令与页面)

### ISSUE THREAD

**Issue by jianghua001** [irisnet/explorer#173]
测试网：fuxi-3001
命令查询#iriscli account  [address]
页面查询： https://testnet.irisplorer.cn/#/address/1/[address] 
balance显示不一致。

**Comment by zhangyelong** [comment]
经确认，explorer v0.4.1 版本中没有处理 irishub v0.4.2 新增的交易类型，导致新类型的交易无法被explorer正确处理，所以balance会出现与链上不匹配的情况
![image](https://user-images.githubusercontent.com/31681438/46242323-09e45780-c3fa-11e8-8b98-149a1de6dd2b.png)
