### ISSUE TITLE
 极验插件无法验证通过

### ISSUE THREAD

**Issue by mahuaibo** [irisnet/explorer#79]
Safari 版本 11.1.2 (13605.3.8) ---- 以前成功过
Chrome 版本 68.0.3440.106（正式版本）---- 以前成功过
Firefox 61.0.1 (64 位) ---- 一直没有成功过

错误信息
Uncaught ReferenceError: getNVCVal is not defined at index.js:1

**Comment by mahuaibo** [comment]
在其他电脑尝试成功了（Chrome 版本 67.0.3396.99（正式版本） （64 位））

还有一个问题是当验证成功10次后，就弹出滑动验证方式，但是从来没有成功过
![image](https://user-images.githubusercontent.com/8769431/44438616-85303d80-a5f2-11e8-8aef-f7b242520409.png)

**Comment by zhangyelong** [comment]
v0.4.2 已修复
